### ISSUE TITLE
Windows/Files with space in their name

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/ocelotl#110]
This issue https://github.com/soctrace-inria/framesoc/issues/96 could append in Ocelotl for everything related with files: config, cache, snapshot, etc.
- [ ] Tests on Linux and Windows
- [ ] Patch if the same problem occurs.

**Comment by ycorre** [comment]
I tested and found no problem with handling files that have space(s) in their name.

**Comment by dosimont** [comment]
Even in the case where directories which contain them have space or weird char in their name?

**Comment by ycorre** [comment]
Well I tried with spaces and had no problem. For weird caracters (such as ":" which is forbidden in Windows), I don't see how that could happen: since i checked for forbidden character and the default save dialog in Java also checks and provides an error if the file name is not valid.
