### ISSUE TITLE
Take into account the weight of aggregates during the pre-aggregation

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/ocelotl#131]
It also necessitates to change the lpaggreg interface to provide a weight for each leaf, and probably change a bit the aggregation algorithm.

**Comment by ycorre** [comment]
How so ? Currently the new leaf weight  value is the addition of all the aggregated leaves (whiich means that the event producer has the same weight than if there was no aggregation). This is necessary to provide correct values in statistics and to draw the aggregation.

So I am not sure how you would like to modify it ?

**Comment by dosimont** [comment]
This is transparent in Ocelotl, but in LPAggreg, each leaf has a weight of 1 and node weight is the sum of the weight of its children. This have an influence on the aggregation, since the node values are "normalized" as a function of this weight. If we pre-aggregate like we do now, new leaves (that are aggregates) have implicitely a weight of 1 ; they should have a weight that is the sum of their children to keep the same weight distribution in the hierarchical tree:

Example:
      A
  B        C
D E       F

Without preaggregation: 
D, E, F weight is 1
B weight is 2
C is 1
A is 3

With pre aggregation removing last hierarchical level:
in Ocelotl current version:
B is 1
C is 1
A is 2
it gives equal weight to B and C

good way  to proceed:
B is 2
C is 1
A is 3
B is more weighted than C

The way to proceed is to associate a weight to each event producer, and to provide explicitely this weight using the LPAggreg interface, instead of letting him doing that in scred.
We will discuss about that IRL.
