### ISSUE TITLE
Temporal mode (states)

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/ocelotl#140]
% and intensity should be computed relatively to the max amplitude reached (given by the y axis in the case of the temporal stacked bar chart), else, we get always 0%.

**Comment by dosimont** [comment]
![diagram](https://cloud.githubusercontent.com/assets/1575332/6040815/5735cfc2-ac76-11e4-833f-9f39f5c9df4a.png)
![diagram](https://cloud.githubusercontent.com/assets/1575332/6040817/5ac4bcd4-ac76-11e4-9890-eab78825ecee.png)
Ex: at the top, sys_select amplitude is 5%, at the botttom, it is almost 50%.
It should be also 50 % at the top.

**Comment by ycorre** [comment]
I don't understand. On my computer, the percentage values are correct and are identical in both view and in the state summary statistics view. Example: 
![diagram](https://cloud.githubusercontent.com/assets/7486662/6041307/7ffe9d3a-ac7b-11e4-9094-aa72b6e17ef7.png)
![diagram](https://cloud.githubusercontent.com/assets/7486662/6041309/88b06616-ac7b-11e4-92a9-4bc89ac1fc4a.png)

**Comment by dosimont** [comment]
Try with TS_record, on flutin : traces/tsrecord/tsrec_long_8min.csv.
