### ISSUE TITLE
Color dialog : back to the old behavior

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/ocelotl#143]
Before, only event types that were involved in the representation were proposed. Since your modifications, all the events registered to Framesoc are shown, which is annoying. I prefer the old behavior, even if it implies code replication. The best solution could be to make the original Framesoc class more generic to fit to our needs.

**Comment by ycorre** [comment]
It is already fixed, but you have to use the latest version of Framesoc (master).

**Comment by dosimont** [comment]
Ok, my bad.
