### ISSUE TITLE
Qualities are always 0 in temporal aggregation snapshots parameter file

### ISSUE THREAD

**Issue by dosimont** [soctrace-inria/ocelotl#152]

**Comment by ycorre** [comment]
With which trace ? I can't reproduce that bug.

**Comment by dosimont** [comment]
Trace name: grenoble_64_cg.C.64
Number of slices: 100
Displayed Start timestamp: 0
Displayed End timestamp: 25746100000
Selected Start timestamp: 0
Selected End timestamp: 25746100000
Metric type: States
Aggregation Operator: Temporal Aggregation
Visualization Operator: Temporal Stacked Bar Chart
Statistics Operator: Leaves State Summary
Max Amplitude Value: 61.42364680233123
Parameter: 0.3671875
Gain: 0.0 - Loss: 0.0
