### ISSUE TITLE
Ocelotl extremely slow leaving processes using all my CPUs

### ISSUE THREAD

**Issue by dbeniamine** [soctrace-inria/ocelotl#188]
Hi,

I'm still working on new Moca traces (I've just updated the importer on the inria gforge), when I try to visualize these traces with Ocelotl, it generate some java processes that keep using (almost) 100% of all my CPUs when Ocelotl has finished to compute the visualization and make Framesoc unresponsive. Furthermore if I quit both Framesoc (by killing it) and eclipse (properly) I still have these 4 processes up an running ...

Here what I can see of them with a `ps`:

    05/02/16 14:31 ✔ david@osage:~
    $ ps aux | grep java
    david     7629  0.0  0.0  12728  2220 pts/4    S+   14:31   0:00 grep --color=auto java
    david    29843  217 81.9 10696832 6584940 ?    Sl   14:08  48:23 /usr/lib/jvm/java-7-oracle/bin/java -Dosgi.requiredJavaVersion=1.7 -XX:MaxPermSize=256m -Xms40m -Xmx7168m -Declipse.pde.launch=true -Dfile.encoding=UTF-8 -classpath /home/david/install/eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar org.eclipse.equinox.launcher.Main -launcher /home/david/install/eclipse/eclipse -name Eclipse -showsplash 600 -product org.eclipse.platform.ide -data /home/david/Work/soctrace/workspace/../runtime-EclipseApplication -configuration file:/home/david/Work/soctrace/workspace/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/ -dev file:/home/david/Work/soctrace/workspace/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os linux -ws gtk -arch x86_64 -nl en_GB -consoleLog
    

Any idea ?

P.S: My traces have 47152 event producers for 405215 events.
P.P.S: There are the trace files: [newMoca.zip](https://github.com/soctrace-inria/ocelotl/files/119189/newMoca.zip)

David

**Comment by ycorre** [comment]
I did not test the trace you provided but that sounds like the overview is still in computation. The overview is launched as a background thread once the main computation is done, but with the number of event producers you have it must consume too much resources.

You can disable it in the Ocelotl options : Overview tab -> uncheck Display Overview.

**Comment by dbeniamine** [comment]
It seems indeed to solve the problem, thanks :)
